name: Package PLG
on:
  workflow_dispatch:
jobs:
  package_and_update:
    permissions: write-all
    runs-on: ubuntu-latest
    container: bobbintb/unraid-cicd
    env:
      name: "bobbintb.system.unraidtemplate"
      author: "bobbintb"
      repo: "UnRAID-Dev-edition"
      launch: "Settings/UnRAID-Dev-edition"
      pluginURL: "https://raw.githubusercontent.com/&author;/&repo;/master/&name;.plg"
      source: "/boot/config/plugins/&name;/&name;"
      icon: "fa-search-minus"
      min: "6.1.9"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download UnRAID-Plugin-Generator
        run: |
          wget https://raw.githubusercontent.com/bobbintb/UnRAID-Plugin-Generator/main/plugin.sh
          chmod +x plugin.sh
      - name: Run UnRAID-Plugin-Generator
        run: |
          ./plugin.sh
          rm plugin.sh
          ls -ls
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ env.VERSION }}
          make_latest: true
          files: |
            *.txz
